export const errorsCodesValues: { [key: string]: string } = {
  E_INVALID_AUTH_UID: 'Wrong login or password',
  E_INVALID_AUTH_PASSWORD: 'Wrong login or password',
  DEFAULT_FIELD_INVALID: 'Invalid field',
  UNKNOWN_ERROR: 'Unknown error',
  E_FIELD_REQUIRED: 'Field required',
  E_EMAIL_INVALID: 'Email invalid',
  E_PASSWORD_INVALID: 'Password invalid',
  E_RANGE_INVALID: 'Invalid range',
  required: 'Field required',
  range: 'Invalid range',
  email: 'Email invalid',
  mobile: 'Invalid phone number',
  confirmed: 'Confirmed validation failed',
  unique: 'Field should be unique',
};
